### ISSUE TITLE
nbr2mp4: unable to open display ""

### ISSUE THREAD

**Issue by nfrik** [cseelye/webex-video-converter#1]
First thank you for the image. 

Why when I run the image with this command:

`docker run -i -t cseelye/webex-video-converter:latest /bin/bash`

I receive this error?

`nbr2mp4: unable to open display ""`

I am running it on Ubuntu 16.04 and X11 is installed on the host.

**Comment by cseelye** [comment]
The container uses an ENTRYPOINT command to set the command being run in the container, so if you want to get a bash shell in the container you will have to override that in your docker command.
e.g.
`docker run -i -t --entrypoint /bin/bash cseelye/webex-video-converter:latest`

You can also look at the source for the `convert` script in this repo for the extra docker run arguments that I typically use for this container.

**Comment by nfrik** [comment]
Thank you for the response. This works if I need to open bash session. Now when I run the following command on a remote linux server throug xterm:

`sudo ./convert 199.arf`

I receive `nbr2mp4: unable to open display "localhost:10.0"`

Is it required to run this script strictly in local environment? (I would check but I don't have virtualization support)

**Comment by cseelye** [comment]
For some crazy reason the webex tools require an X11 server with a display they can connect to, even though they are CLI only and never open any windows. I haven't tried this, but you might be able to get it to work on a remote machine with X11 forwarding (ssh -X and any config required for your xserver).

**Comment by nfrik** [comment]
Great! Everything works if I run it directly on the host machine. I will post here if I find solution regarding X11. I am closing the issue.
